name: Delete Workflow
on:
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-22.04
    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
